[build]
builder = "RAILPACK"
buildCommand = "cd packages/convex-backend && npx convex deploy && cd ../../ && NEXT_PUBLIC_CONVEX_URL=$(npx convex url) pnpm build:starter-convex"

[deploy]
startCommand = "sleep 999999"
restartPolicyType = "never"