[build]
builder = "RAILPACK"
buildCommand = "cd packages/convex-backend && npx convex deploy --cmd 'cd ../../ && pnpm build:starter-convex' --cmd-url-env-var-name NEXT_PUBLIC_CONVEX_URL"

[deploy]
startCommand = "sleep 999999"
restartPolicyType = "never"