[build]
builder = "RAILPACK"
buildCommand = "cd packages/convex-backend && npx convex deploy && cd ../../ && pnpm build:starter-convex"

[deploy]
startCommand = "sleep 999999"
restartPolicyType = "never"