[build]
builder = "nixpacks"
buildCommand = "cd packages/convex-backend && npx convex deploy --cmd 'cd ../../ && build:starter-convex'"

[deploy]
startCommand = "pnpm start:starter-convex"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"