[build]
builder = "RAILPACK"
buildCommand = "pnpm build:trpc-app && cd packages/trpc-backend && pnpm db:migrate && cd ../../"

[deploy]
startCommand = "pnpm start:trpc-app"
restartPolicyType = "never"