[build]
builder = "RAILPACK"
buildCommand = "cd packages/trpc-backend && pnpm db:migrate && cd ../../ && pnpm build:trpc-app"

[deploy]
startCommand = "pnpm start:trpc-app"
restartPolicyType = "never"