[build]
builder = "RAILPACK"
buildCommand = "pnpm build:trpc-app"

[deploy]
startCommand = "pnpm start:trpc-app"
preDeployCommand="cd packages/trpc-backend && pnpm db:migrate"
restartPolicyType = "never"