name: 'electric'

services:
  electric:
    image: docker.io/electricsql/electric:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
    ports:
      - '4000:3000'
    networks:
          - electric-net    

networks:
  electric-net:
    external: true